// ---------- 첫 시즌 백지 로스터 구성 ----------
let INITMK={role:'ALL',scope:'all',target:null};
function renderInitialRosterMarket(){
  const root=managedTeam(DB),squads=setupTeamsForManager(DB);if(!INITMK.target||!squads.some(t=>t.id===INITMK.target))INITMK.target=squads[0].id;
  const target=DB.teams[INITMK.target],R=DB.regions[target.region],openInitial=Object.values(negotiationStore(DB)).filter(n=>n.status==='open'&&n.kind==='initial'&&squads.some(t=>t.id===n.teamId)),errors=initialOrganizationErrors(DB,root);
  const free=Object.values(DB.players).filter(p=>!p.retired&&!p.team&&(INITMK.role==='ALL'||p.role===INITMK.role)&&(INITMK.scope==='all'||isLocalPlayer(p,root.region))).sort((x,y)=>obsOvr(DB,y)-obsOvr(DB,x)||x.age-y.age).slice(0,80);
  const cards=squads.map(t=>{const e=initialSquadErrors(DB,t),lim=initialSquadLimits(DB,t),pay=payroll(DB,t);return `<section class="cfgcard"><div class="cfghead"><b>${esc(t.name)}</b><span class="${e.length?'warn':'hi'}">${t.roster.length}/${lim.max}명 · ${e.length?'미완성':'등록 가능'}</span></div><div class="fin"><div><span>연봉</span><b>${money(pay)}</b><small>예산 ${money(initialSalaryBudget(DB,t))}</small></div><div><span>비로컬</span><b>${teamNonLocalCount(DB,t)}/${nonLocalLimitForTeam(DB,t)}</b></div></div>${e.length?`<p class="hint">${e.map(esc).join(' · ')}</p>`:''}${t.roster.length?t.roster.map(id=>{const p=DB.players[id];return `<div class="mrow"><span><span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> · ${p.age}세 · ${money(p.contract.salary)} · ${p.contract.years}년${p.contract.signingBonus?` · 계약금 ${money(p.contract.signingBonus)}`:''}</span><button class="ghost sm2" data-init-release="${p.id}">FA로 되돌리기</button></div>`}).join(''):'<p class="empty">아직 등록 선수가 없습니다.</p>'}</section>`}).join('');
  const rows=free.map(p=>{const e=recruitmentTarget(DB,p.id),ev=e?.evaluation,evalHere=!!(ev&&ev.teamId===target.id),nid=negotiationId(DB,p.id,'initial',target.id),n=negotiationStore(DB)[nid],chk=initialSignCheck(DB,p,target),stage=n&&n.status==='open'?'협상 중':evalHere?'내부 평가 완료':e?recruitStageLabel(e):'미등록';
    const actions=!e?`<button class="ghost sm2" data-init-interest="${p.id}">관심 등록</button><button class="ghost sm2" data-init-scout="${p.id}">스카우팅</button>`:`<select data-init-priority="${p.id}" aria-label="영입 우선순위">${RECRUIT_PRIORITY.map(x=>`<option value="${x}"${e.priority===x?' selected':''}>${x}순위</option>`).join('')}</select><button class="ghost sm2" data-init-scout="${p.id}">스카우팅</button>${!evalHere?`<button class="ghost sm2" data-init-evaluate="${p.id}"${knowledge(DB,p)<35?' disabled':''}>${ev?'대상 스쿼드 재평가':'내부 평가'}</button>`:''}${evalHere&&chk.ok&&!(n&&n.status==='open')?`<button class="primary sm2" data-init-negotiate="${p.id}">공식 협상</button>`:''}<button class="ghost sm2" data-init-drop="${p.id}">후보 해제</button>`;
    return `<tr><td><input type="checkbox" data-init-select="${p.id}" aria-label="${esc(p.name)} 선택"></td><td><span class="role">${ROLE_KO[p.role]}</span></td><td><b>${esc(p.name)}</b><small class="hint"> · ${stage}</small></td><td>${esc((DB.regions[p.nationality||p.region]||{name:p.nationality||p.region}).name)}</td><td class="num">${p.age}</td><td class="num">${obsOvr(DB,p)}${knowledge(DB,p)<100?'?':''}</td><td>${potText(p)}</td><td class="num">${p.reputation}</td><td class="num">${money(playerMarketValue(DB,p))}</td><td class="num">약 ${money(asking(DB,p,target.region))}</td><td>${actions}${!chk.ok?`<small class="lo"> ${esc(chk.reason)}</small>`:''}</td></tr>`}).join('');
  return `<section class="teamhead"><h2>첫 시즌 로스터 구성</h2><p>${esc(root.name)}에서 커리어를 시작합니다. 모든 구단은 백지 로스터에서 출발하고, 글로벌 FA 시장에서 실제 협상을 거쳐 선수단을 구성합니다.</p></section>
  <section><h3>내 구단 조직</h3>${cards}</section>
  ${MSG?`<p class="msg" role="status">${esc(MSG)}</p>`:''}
  <section><h3>진행 중인 계약 협상</h3>${renderNegotiations(squads.map(t=>t.id))}</section>
  <section><h3>FA 선수 풀</h3><div class="controls"><label>등록 스쿼드<select id="init-target">${squads.map(t=>`<option value="${t.id}"${t.id===INITMK.target?' selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>포지션<select id="init-role"><option value="ALL">전체</option>${ROLES.map(r=>`<option value="${r}"${INITMK.role===r?' selected':''}>${ROLE_KO[r]}</option>`).join('')}</select></label><label>범위<select id="init-scope"><option value="all"${INITMK.scope==='all'?' selected':''}>전 세계</option><option value="region"${INITMK.scope==='region'?' selected':''}>내 지역</option></select></label></div>
  <div class="fin"><div><span>대상 스쿼드</span><b>${esc(target.name)}</b></div><div><span>연봉 예산</span><b>${money(initialSalaryBudget(DB,target))}</b><small>${R.spendingRule==='sfr_top5'&&target.division===1?'SFR 상위 5인 기준 '+money(R.salaryCap)+' · 초과 가능(부담금)':'리그 하드캡 없음'}</small></div><div><span>언어</span><b>공용어 사용</b><small>해외 선수 의사소통 페널티 없음</small></div></div>
  <div class="scroll"><table><thead><tr><th><input type="checkbox" id="init-all" aria-label="전체 선택"></th><th>포지션</th><th>선수</th><th>출신</th><th>나이</th><th>종합</th><th>잠재</th><th>명성</th><th>시장가치</th><th>요구 연봉</th><th>영입 절차</th></tr></thead><tbody>${rows}</tbody></table></div><div class="controls"><button class="ghost" id="init-batch-interest">선택 관심 등록</button><button class="ghost" id="init-batch-scout">선택 일괄 스카우팅</button><span class="hint">최대 10명까지 한 번에 처리합니다.</span></div>
  <p class="hint">관심 등록 → 스카우팅/관찰 → 대상 스쿼드 내부 평가 → 공식 제안 → 선수 측 협상 순서입니다. 경쟁 구단의 정확한 조건은 공개되지 않으며 협상을 오래 끌면 선수를 놓칠 수 있습니다.</p></section>
  <section><h3>등록 마감</h3>${errors.length?`<p class="warn">${errors.map(esc).join(' / ')}</p>`:'<p class="hi">내 구단 로스터 규정을 모두 충족했습니다.</p>'}${openInitial.length?`<p class="warn">진행 중인 계약 협상 ${openInitial.length}건을 먼저 마무리해야 합니다.</p>`:''}<div class="controls"><button class="primary" id="init-final"${errors.length||openInitial.length?' disabled':''}>전 세계 로스터 확정 후 시즌 개막</button><span class="hint">확정하면 AI 구단도 남은 FA 풀에서 같은 계약·등록 핵심 규칙으로 선수단을 구성합니다.</span></div></section>`;
}
function bindInitialRosterMarket(){
  const act=m=>{const y=window.scrollY;MSG=m;saveDB();nav();requestAnimationFrame(()=>window.scrollTo(0,y))};
  $('#init-target').onchange=e=>{INITMK.target=e.target.value;MSG='';nav()};$('#init-role').onchange=e=>{INITMK.role=e.target.value;nav()};$('#init-scope').onchange=e=>{INITMK.scope=e.target.value;nav()};
  document.querySelectorAll('[data-init-interest]').forEach(b=>b.onclick=()=>act(mInterest(DB,b.dataset.initInterest,'B')));
  if($('#init-all'))$('#init-all').onchange=e=>document.querySelectorAll('[data-init-select]').forEach(x=>x.checked=e.target.checked);
  const initSelected=()=>[...document.querySelectorAll('[data-init-select]:checked')].slice(0,10).map(x=>x.dataset.initSelect);
  if($('#init-batch-interest'))$('#init-batch-interest').onclick=()=>{const ids=initSelected();if(!ids.length)return act('선수를 선택하세요');for(const id of ids)mInterest(DB,id,'B');act(ids.length+'명 관심 등록')};
  if($('#init-batch-scout'))$('#init-batch-scout').onclick=()=>{const ids=initSelected();if(!ids.length)return act('선수를 선택하세요');act(scoutPlayers(DB,ids,40,0.1*psOf(DB,DB.teams[managedTeamId(DB)].region)*ids.length))};
  document.querySelectorAll('[data-init-priority]').forEach(el=>el.onchange=()=>act(mInterest(DB,el.dataset.initPriority,el.value)));
  document.querySelectorAll('[data-init-scout]').forEach(b=>b.onclick=()=>act(scoutPlayers(DB,[b.dataset.initScout],40,0.1*psOf(DB,DB.teams[managedTeamId(DB)].region))));
  document.querySelectorAll('[data-init-evaluate]').forEach(b=>b.onclick=()=>act(mEvaluateTarget(DB,b.dataset.initEvaluate,INITMK.target)));
  document.querySelectorAll('[data-init-negotiate]').forEach(b=>b.onclick=()=>act(initialStartNegotiation(DB,b.dataset.initNegotiate,INITMK.target)));
  document.querySelectorAll('[data-init-drop]').forEach(b=>b.onclick=()=>act(mDropInterest(DB,b.dataset.initDrop)));
  document.querySelectorAll('[data-init-release]').forEach(b=>b.onclick=()=>act(initialReleasePlayer(DB,b.dataset.initRelease)));
  bindNegotiationControls(act);
  const fin=$('#init-final');if(fin)fin.onclick=()=>{try{finalizeInitialRosters(DB);MSG='';saveDB();nav();window.scrollTo(0,0)}catch(e){act(e.message||String(e))}};
}

// ---------- 이적 시장 (직접 운영) ----------
let MK={role:'ALL',scope:'region',tab:'fa'};
function recruitStageLabel(e){return !e?'미등록':e.stage==='interest'?'관심':e.stage==='observed'?'관찰 완료':e.stage==='evaluated'?'내부 평가 완료':e.stage==='negotiating'?'협상 중':e.stage==='closed'?(e.result==='signed'?'영입 완료':e.result==='lost_to_rival'?'경쟁 구단 선택':'종료'):e.stage}
function contractTermsText(c){if(!c)return '';const b=c.bonuses||{},xs=[money(c.salary)+' 연봉',c.years+'년'];if(c.signingBonus)xs.push('계약금 '+money(c.signingBonus));if(b.performance)xs.push('성과 '+money(b.performance));if(b.title)xs.push('우승 '+money(b.title));if(b.international)xs.push('국제전 '+money(b.international));if(c.buyout)xs.push('바이아웃 '+money(c.buyout));if(c.option)xs.push((c.option.type==='player'?'선수':'팀')+' 옵션');if(c.promisedRole)xs.push(SQUAD_ROLE_KO[c.promisedRole]||c.promisedRole);return xs.join(' · ')}
function recruitButtons(p,e){
  if(p.team===managedTeamId(DB))return '';
  if(!e)return `<button class="ghost sm2" data-interest="${p.id}">관심 등록</button><button class="ghost sm2" data-scout="${p.id}">스카우팅</button>`;
  const evalBtn=['interest','observed'].includes(e.stage)?`<button class="ghost sm2" data-evaluate="${p.id}"${knowledge(DB,p)<35?' disabled':''}>내부 평가</button>`:'';
  return `<select data-priority="${p.id}" aria-label="영입 우선순위">${RECRUIT_PRIORITY.map(x=>`<option value="${x}"${e.priority===x?' selected':''}>${x}순위</option>`).join('')}</select><button class="ghost sm2" data-scout="${p.id}">스카우팅</button>${evalBtn}<button class="ghost sm2" data-drop="${p.id}">후보 해제</button>`;
}
function renderRecruitmentBoard(){
  const rows=recruitmentBoard(DB).filter(e=>DB.players[e.pid]&&!DB.players[e.pid].retired),rank={A:0,B:1,C:2};
  if(!rows.length)return '<p class="hint">아직 영입 후보가 없습니다. FA나 이적 대상에서 관심 등록 후 스카우팅과 내부 평가를 진행하세요.</p>';
  return rows.sort((a,b)=>(rank[a.priority]??9)-(rank[b.priority]??9)).map(e=>{const p=DB.players[e.pid],ev=e.evaluation,where=p.team?esc(tshort(p.team)):'FA';return `<div class="mrow"><span><b>${e.priority}</b> <span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> · ${where} · ${recruitStageLabel(e)} · 정보 ${knowledge(DB,p)}%${ev?` · 적합도 <b>${ev.fit}</b>/100 · 능력 ${ev.ability[0]}–${ev.ability[1]} · 잠재 ${ev.potential[0]}–${ev.potential[1]} · 예상 역할 ${SQUAD_ROLE_KO[ev.expectedRole]||ev.expectedRole}`:''}</span><span>${recruitButtons(p,e)}${e.stage==='evaluated'&&!p.team?`<button class="primary sm2" data-start-fa="${p.id}">공식 협상</button>`:''}</span></div>`}).join('');
}
function renderNegotiations(teamIds=null){
  const allowed=new Set(teamIds||[managedTeamId(DB)]),negs=Object.values(negotiationStore(DB)).filter(n=>allowed.has(n.teamId)&&n.status==='open');
  if(!negs.length)return '<p class="hint">진행 중인 공식 협상이 없습니다.</p>';
  return negs.map(n=>{const p=DB.players[n.pid],rivals=n.competitors?.length||0;
    if(n.stage==='club'){const ask=n.clubCounter||sellerTransferAsk(DB,p,DB.teams[n.sellerId]);return `<div class="cfgcard"><div class="cfghead"><b>${esc(p.name)} · 이적료 협상</b><span class="hint">${esc(DB.teams[n.sellerId]?.name||'원소속 구단')} · ${n.clubRounds||0}/3라운드</span></div><p class="hint">상대 역제안이 있을 때만 정확한 요구액을 확인할 수 있습니다.</p><div class="controls"><label>이적료 <input type="number" step="0.5" min="0" value="${ask}" data-neg-fee="${n.id}">억</label><button class="primary" data-neg-bid="${n.id}">제안</button>${n.clubCounter?`<button class="ghost" data-accept-seller="${n.id}">역제안 수락</button>`:''}<button class="ghost" data-neg-cancel="${n.id}">협상 종료</button></div></div>`}
    const c=n.counter||n.demand,b=c.bonuses||{};
    return `<div class="cfgcard"><div class="cfghead"><b>${esc(p.name)} · ${n.kind==='renewal'?'재계약':n.kind==='initial'?(esc(DB.teams[n.teamId]?.name||'')+' 창단 계약'):'개인조건'} 협상</b><span class="hint">${n.round}/${n.maxRounds}라운드 · 경쟁 관심 ${rivals}곳</span></div><p><b>${n.counter?'선수 측 역제안':'선수 측 초기 요구'}</b> · ${esc(contractTermsText(c))}</p><div class="controls"><label>연봉 <input type="number" step="0.1" min="0.1" value="${c.salary}" data-neg-sal="${n.id}">억</label><label>기간 <select data-neg-years="${n.id}">${[1,2,3,4].map(y=>`<option value="${y}"${c.years===y?' selected':''}>${y}년</option>`).join('')}</select></label><label>계약금 <input type="number" step="0.1" min="0" value="${c.signingBonus||0}" data-neg-sign="${n.id}">억</label><label>성과 보너스 <input type="number" step="0.1" min="0" value="${b.performance||0}" data-neg-perf="${n.id}">억</label><label>우승 보너스 <input type="number" step="0.1" min="0" value="${b.title||0}" data-neg-title="${n.id}">억</label><label>국제전 보너스 <input type="number" step="0.1" min="0" value="${b.international||0}" data-neg-intl="${n.id}">억</label><label>바이아웃 <input type="number" step="0.5" min="0" value="${c.buyout||0}" data-neg-buyout="${n.id}">억</label><label>옵션 <select data-neg-option="${n.id}"><option value="none"${!c.option?' selected':''}>없음</option><option value="team"${c.option?.type==='team'?' selected':''}>팀 옵션</option><option value="player"${c.option?.type==='player'?' selected':''}>선수 옵션</option></select></label><label>약속 역할 <select data-neg-role="${n.id}">${SQUAD_ROLES.map(x=>`<option value="${x}"${c.promisedRole===x?' selected':''}>${SQUAD_ROLE_KO[x]}</option>`).join('')}</select></label></div><div class="controls"><button class="primary" data-neg-submit="${n.id}">제안 보내기</button>${n.counter?`<button class="ghost" data-neg-accept="${n.id}">역제안 그대로 수락</button>`:''}<button class="ghost" data-neg-cancel="${n.id}">협상 종료</button></div><p class="hint">다른 구단의 정확한 조건은 공개되지 않습니다. FA 협상을 오래 끌면 경쟁 구단을 선택할 수 있습니다.</p></div>`}).join('');
}
function renderMarket(){
  const w=DB.world,t=DB.teams[managedTeamId(DB)],R=DB.regions[t.region],pay=payroll(DB,t),budget=salaryBudget(DB,t);
  const exp=t.roster.map(id=>DB.players[id]).filter(p=>!p.contract||p.contract.until<DB.year);
  const roster=t.roster.map(id=>DB.players[id]);
  const fas=Object.values(DB.players).filter(p=>!p.retired&&!p.team&&(MK.role==='ALL'||p.role===MK.role)&&(MK.scope==='all'||isLocalPlayer(p,t.region))).sort((a,b)=>obsOvr(DB,b)-obsOvr(DB,a)).slice(0,25);
  const tgts=activeTeams(DB,MK.scope==='all'?null:t.region,1).filter(o=>o.id!==t.id).flatMap(o=>o.roster.map(id=>DB.players[id])).filter(p=>p&&p.contract&&(MK.role==='ALL'||p.role===MK.role)).sort((a,b)=>obsOvr(DB,b)-obsOvr(DB,a)).slice(0,25);
  return `<section class="market"><h3>이적 시장 — ${esc(t.name)}</h3>
  <div class="fin"><div><span>보유 자금</span><b>${money(t.finance.cash)}</b></div><div><span>연봉 총액</span><b>${money(pay)}</b><small>${R.spendingRule==='sfr_top5'?`SFR 상위 5인 ${money(regulatedPayroll(DB,t))} / ${money(R.salaryCap)}`:'리그 하드캡 없음'}</small></div><div><span>영입 예산</span><b>${money(Math.max(0,budget-pay))}</b></div><div><span>로스터</span><b>${t.roster.length}/${5+(DB.worldConfig.subs||0)}</b></div></div>
  ${MSG?`<p class="msg" role="status">${esc(MSG)}</p>`:''}
  <h4>진행 중인 협상</h4>${renderNegotiations()}
  <h4>영입 후보 A/B/C</h4>${renderRecruitmentBoard()}
  ${exp.length?`<h4>계약 결정 — 헤드코치 직접 확정</h4>${exp.map(p=>{const n=negotiationStore(DB)[negotiationId(DB,p.id,'renewal')],o=p.contract?.option,opt=o&&o.year===DB.year?o:null;return `<div class="mrow"><span><span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> ${p.age}세 · 종합 ${playerOvr(p)} · ${p.contract?`현재 ${money(p.contract.salary)} · 시장 요구 약 ${money(asking(DB,p,t.region))}`:'무계약 상태 · 정식 계약 필요'}${opt?` · ${opt.type==='team'?'팀':'선수'} 옵션 ${money(opt.salary)}`:''}</span><span>${opt?.type==='team'?`<button class="ghost sm2" data-exercise-option="${p.id}">팀 옵션 행사</button>`:opt?.type==='player'?'<small class="hint">선수 측 옵션 결정</small>':''}${n&&n.status==='open'?'<small class="hi">협상 중</small>':`<button class="primary sm2" data-start-renew="${p.id}">재계약 협상</button>`}</span></div>`}).join('')}`:''}
  <h4>현재 로스터</h4>${roster.map(p=>`<div class="mrow"><span><span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> ${p.age}세 · 종합 ${playerOvr(p)} · ${p.contract?money(p.contract.salary)+' ~'+p.contract.until:''}${starterFor(DB,t,p.role)===p?'':' <small class="hint">후보</small>'}</span><button class="ghost sm2" data-release="${p.id}">방출</button></div>`).join('')}
  ${sponsorBlock(t)}
  <div class="controls" style="margin-top:12px"><div class="seg"><button data-mk="fa" aria-pressed="${MK.tab==='fa'}">FA</button><button data-mk="tr" aria-pressed="${MK.tab==='tr'}">이적 대상</button><button data-mk="coach" aria-pressed="${MK.tab==='coach'}">스태프</button></div>
    <label>포지션<select id="mkrole"><option value="ALL">전체</option>${ROLES.map(r=>`<option value="${r}"${MK.role===r?' selected':''}>${ROLE_KO[r]}</option>`).join('')}</select></label>
    <label>범위<select id="mkscope"><option value="region"${MK.scope==='region'?' selected':''}>내 지역</option><option value="all"${MK.scope==='all'?' selected':''}>전 세계 (비로컬 등록 제한 적용)</option></select></label></div>
  ${MK.tab==='coach'?coachBlock(t):MK.tab==='fa'?fas.map(p=>{const e=recruitmentTarget(DB,p.id),n=negotiationStore(DB)[negotiationId(DB,p.id,'fa')],ask=asking(DB,p,t.region);return `<div class="mrow"><span><span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> ${p.age}세 · 종합 ${obsOvr(DB,p)}${knowledge(DB,p)<100?'?':''} · 잠재 ${potText(p)} · 요구 약 ${money(ask)}${!isLocalPlayer(p,t.region)?` <small>비로컬 · ${esc((DB.regions[playerOriginRegion(p)]||{name:playerOriginRegion(p)||''}).name)}</small>`:''} · <small>${recruitStageLabel(e)}</small></span><span>${recruitButtons(p,e)}${e?.stage==='evaluated'&&!(n&&n.status==='open')?`<button class="primary sm2" data-start-fa="${p.id}">공식 협상</button>`:''}</span></div>`}).join('')||'<p class="hint">조건에 맞는 FA가 없습니다.</p>'
  :tgts.map(p=>{const e=recruitmentTarget(DB,p.id),fee=transferFee(DB,p),n=negotiationStore(DB)[negotiationId(DB,p.id,'transfer')];return `<div class="mrow"><span><span class="role">${ROLE_KO[p.role]}</span> <b>${esc(p.name)}</b> ${esc(tshort(p.team))} · ${p.age}세 · 종합 ${obsOvr(DB,p)}${knowledge(DB,p)<100?'?':''} · 연봉 ${money(p.contract.salary)} ~${p.contract.until} · 시장 이적가 추정 ${money(fee)} · <small>${recruitStageLabel(e)}</small></span><span>${recruitButtons(p,e)}${e?.stage==='evaluated'&&!(n&&n.status==='open')?`<input type="number" step="0.5" min="0" value="${fee}" data-fee="${p.id}" aria-label="이적료">억<button class="primary sm2" data-bid="${p.id}">구단 협상</button>`:''}</span></div>`}).join('')}
  <p class="hint">영입은 관심 등록 → 관찰/스카우팅 → 내부 평가 → 공식 제안 순서입니다. 재계약도 자동 확정되지 않으며 선수 측과 조건을 협상해야 합니다.</p></section>`;
}
function sponsorBlock(t){
  const cur=t.sponsor&&t.sponsor.until>=DB.year?t.sponsor:null, offers=DB.world.sponsorOffers||[];
  return `<h4>메인 스폰서</h4>${cur?`<p>${esc(cur.name)} ${esc(cur.type)} — 기본 ${money(cur.base)}${cur.perWin?` + 승리당 ${money(cur.perWin)}`:''} (${cur.until}년까지)</p>`:offers.map(o=>`<div class="mrow"><span><b>${esc(o.name)}</b> ${esc(o.type)} · 기본 ${money(o.base)}${o.perWin?` + 승리당 ${money(o.perWin)}`:''} · ${o.years}년</span><button class="ghost sm2" data-spon="${o.id}">계약</button></div>`).join('')+'<p class="hint">계약하지 않으면 팬덤에 따라 매년 다시 정해집니다.</p>'}`;
}
function coachBlock(t){
  const ps=psOf(DB,t.region),members=teamStaffMembers(t);ensureFacilities(t);
  const dept=(d)=>members.filter(s=>staffDepartment(s.role)===d),cards=members.slice().sort((a,b)=>staffDepartment(a.role).localeCompare(staffDepartment(b.role))||b.rating-a.rating).map(x=>`<div class="mrow"><span><b>${esc(x.name)}</b> · ${STAFF_ROLES[x.role]} · 능력 ${x.rating} · 연봉 ${money(staffSalary(x,ps))}</span><button class="ghost sm2" data-fire-staff="${x.id}">계약 해지</button></div>`).join('');
  const limits=`코칭팀 ${dept('coach').length}/${STAFF_DEPT_LIMITS.coach} · 분석팀 ${dept('analyst').length}/${STAFF_DEPT_LIMITS.analyst} · 스카우팅팀 ${dept('scout').length}/${STAFF_DEPT_LIMITS.scout}`;
  const market=(DB.staffPool||[]).slice().sort((a,b)=>b.rating-a.rating).map(x=>{const d=staffDepartment(x.role),full=staffDeptCount(t,d)>=STAFF_DEPT_LIMITS[d];return `<div class="mrow"><span><b>${esc(x.name)}</b> · ${STAFF_ROLES[x.role]} · 능력 ${x.rating} · 연봉 ${money(staffSalary(x,ps))}</span><button class="ghost sm2" data-hire-staff="${x.id}"${full?' disabled':''}>${full?'부서 정원':'선임'}</button></div>`}).join('');
  return `<div class="fin"><div><span>헤드코치</span><b>플레이어</b><small>최종 스포츠 결정</small></div><div><span>부서 정원</span><b>${limits}</b><small>범용 수석코치 없음</small></div><div><span>스태프 효과</span><b>전략 ${Math.round(staffProfile(t).draft)} · 분석 ${Math.round(staffProfile(t).analysis)}</b><small>육성 ${Math.round(staffProfile(t).development)} · 스카우팅 ${Math.round(staffProfile(t).scouting)}</small></div></div><h4>현재 스태프</h4>${cards||'<p class="hint">고용된 전문 스태프가 없습니다.</p>'}<h4>스태프 시장</h4>${market}`;
}
function negotiationTermsFromDom(nid){return {salary:+document.querySelector(`[data-neg-sal="${nid}"]`).value,years:+document.querySelector(`[data-neg-years="${nid}"]`).value,signingBonus:+document.querySelector(`[data-neg-sign="${nid}"]`).value,bonuses:{performance:+document.querySelector(`[data-neg-perf="${nid}"]`).value,title:+document.querySelector(`[data-neg-title="${nid}"]`).value,international:+document.querySelector(`[data-neg-intl="${nid}"]`).value},buyout:+document.querySelector(`[data-neg-buyout="${nid}"]`).value||null,option:document.querySelector(`[data-neg-option="${nid}"]`).value==='none'?null:{type:document.querySelector(`[data-neg-option="${nid}"]`).value},promisedRole:document.querySelector(`[data-neg-role="${nid}"]`).value}}
function bindNegotiationControls(act){
  document.querySelectorAll('[data-neg-bid]').forEach(b=>b.onclick=()=>{const n=negotiationStore(DB)[b.dataset.negBid];act(mTransferBid(DB,n.pid,+document.querySelector(`[data-neg-fee="${n.id}"]`).value))});
  document.querySelectorAll('[data-accept-seller]').forEach(b=>b.onclick=()=>act(acceptSellerCounter(DB,b.dataset.acceptSeller)));
  document.querySelectorAll('[data-neg-submit]').forEach(b=>b.onclick=()=>act(submitNegotiationOffer(DB,b.dataset.negSubmit,negotiationTermsFromDom(b.dataset.negSubmit)).msg));
  document.querySelectorAll('[data-neg-accept]').forEach(b=>b.onclick=()=>act(acceptNegotiationCounter(DB,b.dataset.negAccept).msg));
  document.querySelectorAll('[data-neg-cancel]').forEach(b=>b.onclick=()=>act(cancelNegotiation(DB,b.dataset.negCancel)));
}
function bindMarket(){
  const act=m=>{MSG=m;saveDB();nav();const e=document.querySelector('.market');e&&e.scrollIntoView({block:'start'})};
  document.querySelectorAll('[data-spon]').forEach(b=>b.onclick=()=>act(mSponsor(DB,b.dataset.spon)));
  document.querySelectorAll('[data-hire-staff]').forEach(b=>b.onclick=()=>{const x=(DB.staffPool||[]).find(s=>s.id===b.dataset.hireStaff);if(x&&confirm(`${STAFF_ROLES[x.role]} ${x.name}을(를) 선임할까요?\n능력 ${x.rating} · ${STAFF_DEPT_LABEL[staffDepartment(x.role)]}`))act(mHireStaff(DB,b.dataset.hireStaff))});
  document.querySelectorAll('[data-fire-staff]').forEach(b=>b.onclick=()=>{const s=teamStaffMembers(managedTeam(DB)).find(x=>x.id===b.dataset.fireStaff);if(s&&confirm(`${STAFF_ROLES[s.role]} ${s.name}의 계약을 해지할까요?`))act(mReleaseStaff(DB,b.dataset.fireStaff))});
  document.querySelectorAll('[data-exercise-option]').forEach(b=>b.onclick=()=>act(mExerciseTeamOption(DB,b.dataset.exerciseOption)));
  document.querySelectorAll('[data-start-renew]').forEach(b=>b.onclick=()=>act(startNegotiation(DB,b.dataset.startRenew,'renewal').msg));
  document.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>{const p=DB.players[b.dataset.release],cost=p.contract&&p.contract.until>=DB.year?p.contract.salary*(p.contract.until-DB.year+1)*.5:0;if(confirm(`${p.name} 선수를 방출할까요?\n해지금 ${money(cost)}${p.contract?` · 계약 ${p.contract.until}년까지`:''}\n방출 후 즉시 FA가 됩니다.`))act(mRelease(DB,b.dataset.release))});
  document.querySelectorAll('[data-interest]').forEach(b=>b.onclick=()=>act(mInterest(DB,b.dataset.interest,'B')));
  document.querySelectorAll('[data-priority]').forEach(el=>el.onchange=()=>act(mInterest(DB,el.dataset.priority,el.value)));
  document.querySelectorAll('[data-evaluate]').forEach(b=>b.onclick=()=>act(mEvaluateTarget(DB,b.dataset.evaluate)));
  document.querySelectorAll('[data-drop]').forEach(b=>b.onclick=()=>act(mDropInterest(DB,b.dataset.drop)));
  document.querySelectorAll('[data-start-fa]').forEach(b=>b.onclick=()=>act(startNegotiation(DB,b.dataset.startFa,'fa').msg));
  document.querySelectorAll('[data-bid]').forEach(b=>b.onclick=()=>{const id=b.dataset.bid;act(mTransfer(DB,id,+document.querySelector(`[data-fee="${id}"]`).value))});
  document.querySelectorAll('[data-scout]').forEach(b=>b.onclick=()=>act(scoutPlayers(DB,[b.dataset.scout],40,0.1*psOf(DB,DB.teams[managedTeamId(DB)].region))));
  bindNegotiationControls(act);
  document.querySelectorAll('[data-mk]').forEach(b=>b.onclick=()=>{MK.tab=b.dataset.mk;nav()});
  $('#mkrole').onchange=e=>{MK.role=e.target.value;nav()};$('#mkscope').onchange=e=>{MK.scope=e.target.value;nav()};
}
