// ---------- 패치·메타 ----------
let PSET={role:'ALL',q:'',region:'GLOBAL',patch:'ALL',comp:'ALL',period:'ALL',year:'',season:'ALL',split:'ALL',league:'ALL',scope:'ALL',position:'ALL',champ:null};
function patchValueText(v,field){
  if(Array.isArray(v))return v.join('/');
  if(['damageMod','utilityMod','healMod','shieldMod','ccMod','mobilityMod'].includes(field))return Math.round(Number(v)*100)+'%';
  return Number.isFinite(Number(v))?String(Math.round(Number(v)*100)/100):String(v??'');
}
function patchFieldLabel(field){
  return {cooldown:'재사용 대기시간',range:'사거리',cost:'자원 소모',damageMod:'피해량 계수',utilityMod:'유틸리티 효과',healMod:'회복 효과',shieldMod:'보호막 효과',ccMod:'CC 효과',mobilityMod:'이동 효과',offense:'공격 효과',defense:'방어 효과',sustain:'유지력',utility:'유틸리티',haste:'스킬 가속 효과',mobility:'기동성',early:'초반 효과',scaling:'성장 효과'}[field]||field;
}
function noteText(n){
  const why=n.why?` <small>${esc((n.size?PATCH_SIZE_KO[n.size]+' 조정 · ':'')+n.why)}</small>`:'';
  if(n.type==='new')return `<b>신규 챔피언 ${esc(n.def.name)}</b> <small>${n.def.roles.map(r=>ROLE_KO[r]).join('/')} · ${esc(CLASS_KO[ARCH[n.def.arch][0]])} · ${esc(n.def.proEligibleDate)}부터 프로 사용 가능</small>`;
  if(n.type==='rework')return `<b>${esc(championLabel(DB,n.c))}</b> ${n.scope==='major'?'대규모 챔피언 업데이트':'미드스코프 업데이트'} <small>안정 ID ${esc(n.stableId)} 유지 · ${esc(n.why||'')}</small>`;
  if(n.type==='rule')return `<b>${esc(RULE_KO[n.key]||n.key)}</b> ${patchValueText(n.old,n.key)} → ${patchValueText(n.v,n.key)}${why}`;
  if(n.type==='kit')return `<b>${esc(championLabel(DB,n.c))}</b> ${esc(KIT_KO[n.key]||n.key)} ${patchValueText(n.old,n.key)} → ${patchValueText(n.new,n.key)}${why}`;
  if(n.type==='skill')return `<b>${esc(championLabel(DB,n.c))} ${esc(n.slot)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`;
  if(n.type==='base')return `<b>${esc(championLabel(DB,n.c))}</b> ${{ad:'공격력',hp:'체력',arm:'방어력',mr:'마법 저항력',adg:'성장 공격력',hpg:'성장 체력',armg:'성장 방어력',mrg:'성장 마법 저항력',ms:'이동 속도',range:'기본 공격 사거리',resource:'자원',resourceRegen:'자원 회복'}[n.key]||esc(n.key)} ${patchValueText(n.old,n.key)} → ${patchValueText(n.new,n.key)}${why}`;
  if(n.type==='item'){const d=DB.patch.itemDefs?.[n.id];return `<b>아이템 · ${esc(d?.name||n.id)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`}
  if(n.type==='item_new')return `<b>신규 아이템 · ${esc(n.def.name)}</b> ${n.def.cost}골드 <small>${esc(n.why||'')}</small>`;
  if(n.type==='item_remove'){const d=DB.patch.itemDefs?.[n.id];return `<b>아이템 삭제 · ${esc(d?.name||n.id)}</b> <small>${esc(n.why||'')}</small>`}
  if(n.type==='rune'){const d=DB.patch.runeDefs?.[n.id];return `<b>룬 · ${esc(d?.name||n.id)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`}
  if(n.type==='rune_new')return `<b>신규 룬 · ${esc(n.def.name)}</b> <small>${n.def.kind==='keystone'?'핵심 룬':'보조 룬'} · ${esc(n.why||'')}</small>`;
  if(n.type==='rune_remove'){const d=DB.patch.runeDefs?.[n.id];return `<b>룬 삭제 · ${esc(d?.name||n.id)}</b> <small>${esc(n.why||'')}</small>`}
  return esc(n.text||n.why||'');
}
function viewPatch(){
  const pt=DB.patches, list=[...pt.list].reverse(), prev=[...(pt.prev||[])].reverse();
  const rid=PSET.region==='GLOBAL'?null:PSET.region,hist=DB.metaHistory||[],comps=[...new Set(hist.map(x=>x.comp).filter(Boolean))].sort(),patches=[...new Set(hist.map(x=>x.patch).filter(Boolean))].sort().reverse(),seasons=[...new Set(hist.map(x=>x.season).filter(Boolean))].sort().reverse(),splits=[...new Set(hist.map(x=>x.split).filter(x=>x!==null&&x!==undefined))].sort(),leagues=[...new Set(hist.map(x=>x.league).filter(Boolean))].sort(),today=DB.worldDate,from=PSET.period==='30'?addDays(today,-30):PSET.period==='90'?addDays(today,-90):PSET.period==='YEAR'?today.slice(0,4)+'-01-01':null,filter={region:rid||undefined,patch:PSET.patch==='ALL'?undefined:PSET.patch,comp:PSET.comp==='ALL'?undefined:PSET.comp,season:PSET.season==='ALL'?undefined:PSET.season,year:PSET.year||undefined,split:PSET.split==='ALL'?undefined:PSET.split,league:PSET.league==='ALL'?undefined:PSET.league,scope:PSET.scope==='ALL'?undefined:PSET.scope,position:PSET.position==='ALL'?undefined:PSET.position,from:from||undefined,to:PSET.period==='ALL'?undefined:today},filtered=!!(filter.patch||filter.comp||filter.season||filter.year||filter.split||filter.league||filter.scope||filter.position||filter.from),mt=filtered?metaTableFiltered(DB,filter):metaTable(DB,rid),G=mt[0]?.sample||0;
  const rows=mt.filter(x=>(PSET.role==='ALL'||x.c.roles.includes(PSET.role))&&(!PSET.q||championDisplayName(x.c).toLowerCase().includes(PSET.q.toLowerCase())||x.c.name.toLowerCase().includes(PSET.q.toLowerCase())));
  const tier=x=>x.pres>=0.35?'S':x.pres>=0.18?'A':x.pres>=0.08?'B':x.pres>0?'C':'-';
  const dc=PSET.champ&&DB.patch.champions[PSET.champ], ds=dc&&dc.skills, mi=dc?championMetaInsights(DB,dc.id,filter):null;
  const insightList=(arr,nameFn)=>arr&&arr.length?arr.map(([id,x])=>esc(nameFn(id))+' '+x.g+'전 '+Math.round(x.w/Math.max(1,x.g)*100)+'%').join(' · '):'표본 없음';
  const insight=dc&&mi?'<section id="champmeta"><h4>대회 메타 인사이트</h4><div class="cards"><article class="card"><b>주요 선수</b><p>'+insightList(mi.players,id=>DB.players[id]?.name||id)+'</p></article><article class="card"><b>주요 팀</b><p>'+insightList(mi.teams,id=>DB.teams[id]?.name||id)+'</p></article><article class="card"><b>동일 포지션 매치업</b><p>'+insightList(mi.matchups,id=>championLabel(DB,id))+'</p></article><article class="card"><b>최근 흐름</b><p>'+(mi.recent.length?mi.recent.map(x=>x.win?'W':'L').join(' · '):'표본 없음')+'</p></article></div></section>':'';
  const detail=dc?`<section id="champdetail"><div class="cfghead"><h3>${esc(championDisplayName(dc))}</h3><button class="ghost sm2" id="pclose">닫기</button></div><p>${dc.roles.map(r=>ROLE_KO[r]).join('/')} · ${esc(CLASS_KO[dc.cls])} · ${esc(dc.dmg)} · 프로 ${championProEligible(DB,dc)?'사용 가능':`사용 제한 (~${esc(dc.proEligibleDate||'')})`}</p><div class="fin"><div><span>체력</span><b>${Math.round(dc.base.hp)}</b><small>+${dc.base.hpg}/레벨</small></div><div><span>방어력 / 마법 저항력</span><b>${Math.round(dc.base.arm)} / ${Math.round(dc.base.mr)}</b><small>+${dc.base.armg} / +${dc.base.mrg}</small></div><div><span>공격력</span><b>${Math.round(dc.base.ad)}</b><small>+${dc.base.adg}/레벨</small></div><div><span>공속 / 성장</span><b>${dc.base.as}</b><small>+${dc.base.asg}%</small></div><div><span>사거리 / 이동속도</span><b>${dc.base.range} / ${dc.base.ms}</b></div><div><span>자원</span><b>${dc.base.resource||'없음'}</b><small>${dc.base.resource?`성장 +${dc.base.resourceg} · 회복 ${dc.base.resourceRegen}`:''}</small></div></div><h4>${dc.detailSource==='riot_ddragon'?'패치 원천 연동 스킬 데이터':'스킬 시뮬레이션 데이터'}</h4><div class="cards">${Object.values(ds||{}).map(sk=>`<article class="card"><b>${sk.slot}${sk.name?` · ${esc(sk.name)}`:''}</b><p>${sk.sourceDescription?esc(sk.sourceDescription):(sk.kind==='ultimate'?'궁극기':sk.kind==='passive'?'패시브':'기본 스킬')+' · '+(sk.damageType?sk.damageType+' · ':'')+sk.effects.map(esc).join(', ')}</p><small>${sk.sourceDescription?'시뮬레이션 해석 · ':''}효과 강도 ${sk.power}${sk.cooldown?` · 재사용 ${sk.cooldown}초`:''}${sk.baseDamage?.length?` · 기본 피해 ${sk.baseDamage.join('/')}`:''}${Object.keys(sk.ratios||{}).length?` · 계수 ${Object.entries(sk.ratios).map(([k,v])=>k.toUpperCase()+' '+v).join(', ')}`:''}${sk.cc?` · CC ${esc(sk.cc.type||'있음')}${sk.cc.duration?' '+sk.cc.duration+'초':''}`:''}${sk.heal?' · 회복':''}${sk.shield?' · 보호막':''}${sk.range?.length?' · 사거리 '+sk.range.join('/'):''}</small></article>`).join('')}</div><p class="hint">${dc.detailSource==='riot_ddragon'?`Riot Data Dragon ${esc(dc.detailVersion||'')}의 한국어 스킬 설명과 공개 스탯이 연결되어 있습니다. Data Dragon에 없는 세부 계수는 시뮬레이션 파생값을 유지합니다.`:'현재 스킬 수치는 경기 시뮬레이션용 대체 구조입니다. 권위 데이터가 연결되면 자동 교체됩니다.'}</p></section>`:'';
  const sysRows=patchEvidenceRows(DB),activeItems=Object.values(DB.patch.itemDefs||{}).filter(x=>x.active!==false),activeRunes=Object.values(DB.patch.runeDefs||{}).filter(x=>x.active!==false);
  const topSystem=(kind,defs)=>defs.map(d=>({d,e:systemUsageEvidence(DB,kind,d.id,sysRows)})).filter(x=>x.e.eligible>0).sort((a,b)=>b.e.usage-a.e.usage).slice(0,5).map(x=>esc(x.d.name)+' '+Math.round(x.e.usage*100)+'%').join(' · ')||'아직 표본 없음';
  const tierCount=Object.fromEntries(['starter','component','boots','final','consumable','special'].map(k=>[k,activeItems.filter(x=>x.tier===k).length])),runeTree=Object.values(DB.patch.runes||{}).map(st=>esc(st.nameKo||st.name||st.key)+' '+(st.slots||[]).reduce((n,s)=>n+s.filter(id=>DB.patch.runeDefs?.[id]?.active!==false).length,0)+'개').join(' · ');
  const systemMeta=`<section><h3>아이템 / 룬 메타</h3><div class="cards"><article class="card"><b>아이템 ${activeItems.length}개 활성</b><p>${topSystem('item',activeItems)}</p><small>시작 ${tierCount.starter} · 조합 ${tierCount.component} · 장화 ${tierCount.boots} · 완성 ${tierCount.final} · 소모품 ${tierCount.consumable} · 특수 ${tierCount.special}. 아이템 패치는 엔진이 자동 계산하며 가격·효과 변화가 해당 아이템과 잘 맞는 챔피언의 경기력과 메타 가치에 반영됩니다.</small></article><article class="card"><b>룬 ${activeRunes.length}개 활성</b><p>${topSystem('rune',activeRunes)}</p><small>${runeTree}. 룬 조합은 엔진이 자동 처리하며 룬 버프·너프가 수혜 챔피언의 밴픽 우선순위와 경기력에 반영됩니다.</small></article></div><p class="hint">기준 데이터: Riot Data Dragon ${esc(DB.patch.systemSource?.version||'')} · 소환사의 협곡 아이템 ${DB.patch.systemSource?.itemCount||0}개 · 룬 ${DB.patch.systemSource?.runeCount||0}개 / ${DB.patch.systemSource?.runeStyleCount||0}계열</p></section>`;

  return `<section class="teamhead"><h2>패치 ${esc(DB.patch.id)}</h2><p>패치 엔진은 대회 표본, 밴픽 압력, 승률, 최근 추세, 실제 포지션, 지역·국제전 확산, 상위팀·선수 집중도와 플렉스 여부를 함께 진단합니다. 챔피언뿐 아니라 아이템·룬·시스템 변화도 자동으로 챔피언별 메타 가치에 환산되며, 신규 챔피언·신규/삭제 아이템·룬과 미드스코프/대규모 리워크가 장기적으로 발생합니다.</p><p class="hint">챔피언 ${Object.keys(DB.patch.champions).length}명 · 공식 데이터 ${DB.patch.championSource?.matched||0}/${DB.patch.championSource?.total||Object.keys(DB.patch.champions).length} · 한국어 설명 ${DB.patch.championSource?.localized||0}/${DB.patch.championSource?.total||Object.keys(DB.patch.champions).length} · 아이템 ${activeItems.length} · 룬 ${activeRunes.length} · 이번 패치 대회 경기 ${G}판${pt.nextDate?` · 다음 패치 ${esc(pt.nextDate)}`:''}</p></section>
  ${detail}${insight}${systemMeta}
  <section><h3>현재 메타</h3><div class="controls"><label>지역<select id="pregion"><option value="GLOBAL">글로벌</option>${Object.values(DB.regions).map(r=>`<option value="${r.id}"${PSET.region===r.id?' selected':''}>${esc(r.name||r.leagueName||r.id)}</option>`).join('')}</select></label><label>패치<select id="ppatch"><option value="ALL">전체</option>${patches.map(x=>`<option value="${esc(x)}"${PSET.patch===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>대회<select id="pcomp"><option value="ALL">전체</option>${comps.map(x=>`<option value="${esc(x)}"${PSET.comp===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>기간<select id="pperiod"><option value="ALL">전체</option><option value="30"${PSET.period==='30'?' selected':''}>최근 30일</option><option value="90"${PSET.period==='90'?' selected':''}>최근 90일</option><option value="YEAR"${PSET.period==='YEAR'?' selected':''}>올해</option></select></label><label>연도<input id="pyear" type="number" min="2026" value="${esc(PSET.year)}" placeholder="전체"></label><label>시즌<select id="pseason"><option value="ALL">전체</option>${seasons.map(x=>`<option value="${esc(x)}"${PSET.season===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>스플릿<select id="psplit"><option value="ALL">전체</option>${splits.map(x=>`<option value="${esc(x)}"${String(PSET.split)===String(x)?' selected':''}>${esc(SPLIT_NAME?.[x]||x)}</option>`).join('')}</select></label><label>리그<select id="pleague"><option value="ALL">전체</option>${leagues.map(x=>`<option value="${esc(x)}"${PSET.league===x?' selected':''}>${esc((DB.regions[x]&&DB.regions[x].leagueName)||x)}</option>`).join('')}</select></label><label>범위<select id="pscope"><option value="ALL">전체</option><option value="DOM"${PSET.scope==='DOM'?' selected':''}>국내</option><option value="INTL"${PSET.scope==='INTL'?' selected':''}>국제</option></select></label><label>실제 픽<select id="pposition"><option value="ALL">전체</option><option value="TOP"${PSET.position==='TOP'?' selected':''}>탑</option><option value="JGL"${PSET.position==='JGL'?' selected':''}>정글</option><option value="MID"${PSET.position==='MID'?' selected':''}>미드</option><option value="ADC"${PSET.position==='ADC'?' selected':''}>원딜</option><option value="SUP"${PSET.position==='SUP'?' selected':''}>서포터</option></select></label><label>포지션<select id="prole"><option value="ALL">전체</option>${ROLES.map(r=>`<option value="${r}"${PSET.role===r?' selected':''}>${ROLE_KO[r]}</option>`).join('')}</select></label><label>검색<input id="pq" value="${esc(PSET.q)}" placeholder="챔피언 이름"></label></div>
  <div class="scroll"><table class="champs"><thead><tr><th>티어</th><th>챔피언</th><th>포지션</th><th>역할군</th><th>밴픽률</th><th>픽</th><th>밴</th><th>승률</th><th>프로 사용</th><th>초반</th><th>후반</th><th>CC</th><th>폭딜</th></tr></thead><tbody>
  ${rows.slice(0,60).map(x=>`<tr><td><b class="tier t${tier(x)}">${tier(x)}</b></td><td><button class="linklike" data-champ="${x.c.id}"><b>${esc(championDisplayName(x.c))}</b></button></td><td>${x.c.roles.map(r=>ROLE_KO[r]).join('/')}</td><td>${CLASS_KO[x.c.cls]}</td><td class="num">${Math.round(x.pres*100)}%</td><td class="num">${x.p}</td><td class="num">${x.b}</td><td class="num">${x.wr===null?'—':Math.round(x.wr*100)+'%'}</td><td>${x.eligible?'<span class="hi">가능</span>':`<span class="lo">제한</span><small>${esc(x.c.proEligibleDate||'')}</small>`}</td><td><span class="pip" style="--v:${x.c.kit.early}">${x.c.kit.early}</span></td><td><span class="pip" style="--v:${x.c.kit.late}">${x.c.kit.late}</span></td><td><span class="pip" style="--v:${x.c.kit.cc}">${x.c.kit.cc}</span></td><td><span class="pip" style="--v:${x.c.kit.burst}">${x.c.kit.burst}</span></td></tr>`).join('')}
  </tbody></table></div>${rows.length>60?`<p class="hint">상위 60명만 표시합니다. 포지션이나 검색으로 좁혀 보세요.</p>`:''}</section>
  <section><h3>패치 노트</h3>${list.length?list.map((p,i)=>`<details class="pnote"${i===0?' open':''}><summary><b>${esc(p.id)}</b> <small>${esc(p.date)}${p.major?' · 대형 패치':''} · 변경 ${p.notes.length}건</small></summary><ul>${p.notes.map(n=>`<li>${noteText(n)}</li>`).join('')}</ul></details>`).join(''):'<p class="empty">커리어를 시작하면 시즌 개막 패치가 적용됩니다.</p>'}
  ${prev.length?`<details class="pnote"><summary>지난 시즌 패치 ${prev.length}개</summary>${prev.map(p=>`<p><b>${esc(p.id)}</b> <small>${esc(p.date)}</small><br>${p.notes.map(noteText).join(' · ')}</p>`).join('')}</details>`:''}</section>`;
}
function bindPatch(){document.querySelectorAll('[data-champ]').forEach(b=>b.onclick=()=>{PSET.champ=b.dataset.champ;nav()});if($('#pclose'))$('#pclose').onclick=()=>{PSET.champ=null;nav()};$('#pregion').onchange=e=>{PSET.region=e.target.value;nav()};$('#ppatch').onchange=e=>{PSET.patch=e.target.value;nav()};$('#pcomp').onchange=e=>{PSET.comp=e.target.value;nav()};$('#pperiod').onchange=e=>{PSET.period=e.target.value;nav()};$('#pyear').onchange=e=>{PSET.year=e.target.value;nav()};$('#pseason').onchange=e=>{PSET.season=e.target.value;nav()};$('#psplit').onchange=e=>{PSET.split=e.target.value;nav()};$('#pleague').onchange=e=>{PSET.league=e.target.value;nav()};$('#pscope').onchange=e=>{PSET.scope=e.target.value;nav()};$('#pposition').onchange=e=>{PSET.position=e.target.value;nav()};$('#prole').onchange=e=>{PSET.role=e.target.value;nav()};$('#pq').onchange=e=>{PSET.q=e.target.value;nav()}}
