function skillRangeText(skill,champion){
  const source=champion?.riotAlias&&CHAMPION_SOURCE_SNAPSHOT.champions[champion.riotAlias]?.spells.find(x=>x.slot===skill.slot);
  if(source?.rangeDisplay&&skill.source?.version===CHAMPION_SOURCE_SNAPSHOT.version&&JSON.stringify(source.range)===JSON.stringify(skill.range))return source.rangeDisplay;
  if(skill.rangeDisplay&&(!source||JSON.stringify(source.range)===JSON.stringify(skill.range)))return skill.rangeDisplay;
  const values=[...new Set((skill.range||[]).filter(Number.isFinite))];
  if(!values.length)return '';
  if(values.some(v=>v>=20000))return '범위 확인 중';
  if(values.every(v=>v===0))return '자신 중심';
  return '시전 거리 '+values.join('/');
}
// ---------- 패치·메타 ----------
function patchValueText(v,field){
  if(Array.isArray(v))return v.join('/');
  if(['damageMod','utilityMod','healMod','shieldMod','ccMod','mobilityMod','xpBonus','bonusPower','jungleMobility'].includes(field))return Math.round(Number(v)*100)+'%';
  return Number.isFinite(Number(v))?String(Math.round(Number(v)*100)/100):String(v??'');
}
function patchFieldLabel(field){
  return {cooldown:'재사용 대기시간',range:'사거리',cost:'자원 소모',damageMod:'피해량 계수',utilityMod:'유틸리티 효과',healMod:'회복 효과',shieldMod:'보호막 효과',ccMod:'CC 효과',mobilityMod:'이동 효과',offense:'공격 효과',defense:'방어 효과',sustain:'유지력',utility:'유틸리티',haste:'스킬 가속 효과',mobility:'기동성',early:'초반 효과',scaling:'성장 효과'}[field]||field;
}
function noteText(n){
  const why=n.why?` <small>${esc((n.size?PATCH_SIZE_KO[n.size]+' 조정 · ':'')+n.why)}</small>`:'';
  if(n.type==='new')return `<b>신규 챔피언 ${esc(n.def.name)}</b> <small>${n.def.roles.map(r=>ROLE_KO[r]).join('/')} · ${esc(CLASS_KO[ARCH[n.def.arch][0]])} · ${esc(n.def.proEligibleDate)}부터 프로 사용 가능</small>`;
  if(n.type==='rework')return `<b>${esc(championLabel(DB,n.c))}</b> ${n.scope==='major'?'대규모 챔피언 업데이트':'미드스코프 업데이트'} <small>안정 ID ${esc(n.stableId)} 유지 · ${esc(n.why||'')}</small>`;
  if(n.type==='role_quest')return `<b>${esc(ROLE_KO[n.role])} 퀘스트</b> ${esc(ROLE_QUEST_LABELS[n.field]||n.field)} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`;
  if(n.type==='rule')return `<b>${esc(RULE_KO[n.key]||n.key)}</b> ${patchValueText(n.old,n.key)} → ${patchValueText(n.v,n.key)}${why}`;
  if(n.type==='kit')return `<b>${esc(championLabel(DB,n.c))}</b> ${esc(KIT_KO[n.key]||n.key)} ${patchValueText(n.old,n.key)} → ${patchValueText(n.new,n.key)}${why}`;
  if(n.type==='skill')return `<b>${esc(championLabel(DB,n.c))} ${esc(n.slot)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`;
  if(n.type==='base')return `<b>${esc(championLabel(DB,n.c))}</b> ${{ad:'공격력',hp:'체력',arm:'방어력',mr:'마법 저항력',adg:'성장 공격력',hpg:'성장 체력',armg:'성장 방어력',mrg:'성장 마법 저항력',ms:'이동 속도',range:'기본 공격 사거리',resource:'자원',resourceRegen:'자원 회복'}[n.key]||esc(n.key)} ${patchValueText(n.old,n.key)} → ${patchValueText(n.new,n.key)}${why}`;
  if(n.type==='item'){const d=DB.patch.itemDefs?.[n.id];return `<b>아이템 · ${esc(d?.name||n.id)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`}
  if(n.type==='item_new')return `<b>신규 아이템 · ${esc(n.def.name)}</b> ${n.def.cost}골드 <small>${esc(n.why||'')}</small>`;
  if(n.type==='item_remove'){const d=DB.patch.itemDefs?.[n.id];return `<b>아이템 삭제 · ${esc(d?.name||n.id)}</b> <small>${esc(n.why||'')}</small>`}
  if(n.type==='rune'){const d=DB.patch.runeDefs?.[n.id];return `<b>룬 · ${esc(d?.name||n.id)}</b> ${esc(patchFieldLabel(n.field))} ${patchValueText(n.old,n.field)} → ${patchValueText(n.new,n.field)}${why}`}
  if(n.type==='rune_new')return `<b>신규 룬 · ${esc(n.def.name)}</b> <small>${n.def.kind==='keystone'?'핵심 룬':'보조 룬'} · ${esc(n.why||'')}</small>`;
  if(n.type==='rune_remove'){const d=DB.patch.runeDefs?.[n.id];return `<b>룬 삭제 · ${esc(d?.name||n.id)}</b> <small>${esc(n.why||'')}</small>`}
  return esc(n.text||n.why||'');
}
function patchParticipantControls(db,state){
  const publicFacets=metaHistoryFacets(db),privateFacets=ownPracticeFacets(db),facets={teams:[...new Set([...publicFacets.teams,...privateFacets.teams])],players:[...new Set([...publicFacets.players,...privateFacets.players])]},label=(kind,id)=>kind==='player'?(db.players[id]?.name||id):(db.teams[id]?.name||id),options=(kind,ids,selected)=>[...new Set([...ids,...(selected&&selected!=='ALL'?[selected]:[])])].map(id=>`<option value="${esc(id)}"${selected===id?' selected':''}>${esc(label(kind,id))} · ${esc(id)}</option>`).join('');
  const query=(state.playerSearch||'').trim().toLowerCase(),players=facets.players.filter(id=>!query||(label('player',id)+' '+id).toLowerCase().includes(query));
  return `<div class="filters"><label>진영<select id="pcolor"><option value="ALL">전체</option><option value="BLUE"${state.color==='BLUE'?' selected':''}>블루</option><option value="RED"${state.color==='RED'?' selected':''}>레드</option></select></label><label>기록 팀<select id="pteam"><option value="ALL">전체</option>${options('team',facets.teams,state.team)}</select></label><label>맞대결 상대<select id="popponent"><option value="ALL">전체</option>${options('team',facets.teams,state.opponent)}</select></label><label>기록 선수 검색<input id="pplayersearch" value="${esc(state.playerSearch||'')}" placeholder="선수명 또는 ID"></label><label>기록 선수<select id="pplayer"><option value="ALL">전체</option>${options('player',players.slice(0,80),state.player)}</select></label></div><p class="hint">${players.length>80?'선수 검색 결과 중 80명 표시 · 검색으로 좁히세요. ':''}기록 당시 소속과 출전 ID로 선택합니다. 선수 필터의 밴 귀속은 해당 선수 출전 구단의 밴이며 개인의 밴 결정으로 간주하지 않습니다. 미상 ID는 선택한 팀·선수·상대로 추정하지 않습니다.</p>`;
}
function patchBanAttributionCard(db,filter,champ=null){
  const a=metaBanAttribution(db,filter),participant=!!(filter.team||filter.player||filter.opponent||filter.color),scoped=!!(participant||filter.region),label=participant?'선택한 쪽의 구단 밴':filter.region?'선택 지역 직접 밴':'귀속 확인 밴',name=id=>championDisplayName(db.patch.champions[id])||id;
  const top=Object.entries(a.champions).filter(([,x])=>x.own>0).sort((x,y)=>y[1].own-x[1].own||x[0].localeCompare(y[0])).slice(0,5).map(([id,x])=>esc(name(id))+' '+x.own+'회').join(' · ')||'귀속 확인 표본 없음',selected=champ?(a.champions[champ]||{own:0,opponent:0,unknown:0}):null;
  return `<section><h3>기록 경기의 밴 귀속</h3><p>${label} ${a.own}회${scoped?' · '+(participant?'상대 구단 밴 ':'상대 지역 밴 ')+a.opponent+'회':''} · 귀속 미상 ${a.unknown}회</p><p>${top}</p>${selected?'<p>'+esc(name(champ))+' · '+label+' '+selected.own+' · 상대 '+selected.opponent+' · 미상 '+selected.unknown+'</p>':''}<small>필터 경기 ${a.games}판 · 귀속 확인 ${a.knownGames}판 · 미상 ${a.unknownGames}판. 기존 밴 통계는 해당 지역이 참가한 경기의 전체 밴 노출입니다. 팀·선수·맞대결 선택 시에도 표의 밴은 필터 경기의 전체 노출이며, 직접 밴은 여기서 구분합니다. 이 구분은 기록 당시 지역과 실제 밴을 사용하며 과거 미상 기록의 귀속을 추정하지 않습니다. 포지션은 픽에만 적용하며 밴 포지션은 추정하지 않습니다.</small></section>`;
}
function patchSideCoverageCard(db,filter){
  const c=metaSideCoverage(db,filter),line=color=>{const s=c[color];return (color==='BLUE'?'블루':'레드')+' '+s.games+'전 · '+(s.games?Math.round(s.wins/s.games*100)+'%':'승률 표본 없음')};
  return `<section><h3>기록 진영 비교</h3><p>${line('BLUE')} · ${line('RED')}</p><small>진영 외 같은 조건의 경기 ${c.games}판 · 진영 확인 ${c.knownGames}판 · 미상 ${c.unknownGames}판 (${c.unknownSides}쪽). 선택한 팀·선수·지역의 실제 경기 승패를 비교합니다. 진영을 선택하면 픽·승률과 직접 밴은 그 진영만 집계하며 표의 밴은 경기 전체 노출입니다. 과거 미상 진영은 추정하지 않습니다. 적은 표본과 패치·상대 차이로 승률이 달라질 수 있으며 진영의 인과적 우위를 뜻하지 않습니다.</small></section>`;
}
function patchCompositionCard(db,cid,filter){
  const a=championCompositionInsights(db,cid,filter),name=id=>db.patch.champions[id]?championDisplayName(db.patch.champions[id]):id;
  const rows=a.pairs.map(x=>`<li>${esc(name(x.champ))} · 함께 ${x.g}전 ${x.w}승 (${Math.round(x.wr*100)}%) · 선택 챔피언 출전 중 ${Math.round(x.presence*100)}%</li>`).join('');
  return `<section id="champcomposition"><h4>기록된 같은 팀 조합 · ${esc(name(cid))}</h4><p>선택 챔피언 출전 ${a.sample}쪽 · 5픽 확인 ${a.complete}쪽 · 불완전 ${a.partial}쪽 · 챔피언 미상 ${a.unknownPicks}픽</p>${rows?'<ul>'+rows+'</ul>':'<p>함께 픽된 챔피언 표본 없음</p>'}<small>같은 팀의 기록된 동시 픽 빈도순 상위 8명입니다. 팀·선수·진영·포지션은 선택 챔피언의 출전을 고르며, 함께한 선수는 다른 포지션도 포함합니다. 출전 빈도 분모는 선택 챔피언 출전 쪽 수이고 각 승률 분모는 해당 동시 픽 횟수입니다. 불완전 기록의 빈도는 확인된 동시 픽 비율이며 미상 동료의 부재를 뜻하지 않습니다. 적은 표본·패치·상대 차이가 영향을 주므로 조합의 인과적 시너지나 픽 순서를 뜻하지 않습니다. 미상 챔피언·소속·진영은 추정하지 않습니다.</small></section>`;
}
function patchDraftOrderCard(db,cid,filter){
  const a=draftOrderInsights(db,cid,filter),rate=(g,w)=>g?Math.round(w/g*100)+'%':'승률 표본 없음',name=id=>db.patch.champions[id]?championDisplayName(db.patch.champions[id]):id;
  const before=a.preceding.map(x=>esc(name(x.champ))+' '+x.g+'회').join(' · ')||'확인 표본 없음';
  return `<section id="champdraftorder"><h4>기록된 실제 픽 순서</h4><p>선택 챔피언 출전 ${a.appearances}쪽 · 순서 확인 ${a.known}쪽 · 미상 ${a.unknown}쪽</p><p>드래프트 전체 첫 픽 ${a.opening}전 ${a.openingWins}승 (${rate(a.opening,a.openingWins)}) · 그 외 후속 픽 ${a.followup}전 ${a.followupWins}승 (${rate(a.followup,a.followupWins)})</p><p>선택 챔피언 쪽의 픽 순번: ${a.slots.map((n,i)=>(i+1)+'번째 '+n+'회').join(' · ')}</p><p>앞서 선택된 같은 팀 챔피언: ${before}</p><small>실제 공개 픽·밴 선택 로그가 최종 픽·밴과 일치하는 기록만 사용합니다. 전체 첫 픽은 블루나 구단의 첫 픽과 다를 수 있습니다. 기존 역할순 배열과 출처 없는 재현 순서는 미상으로 남깁니다. 조건은 선택한 챔피언 출전에 적용하며 앞선 동료의 포지션은 제한하지 않습니다. 승률 분모는 각 확인된 첫픽/후속픽 출전 수이며 적은 표본·패치·상대 차이가 영향을 줍니다. 선택 순서의 인과적 우위나 상대의 숨은 의도를 뜻하지 않습니다.</small></section>`;
}
function patchAnalystCard(db,filter,cid=null){
  const a=ownAnalystInterpretation(db,filter,cid);if(!a.allowed)return '<section id="analystreport"><h3>분석가의 기록 해석</h3><p>현재 관리 권한이 있는 구단·2군만 조회할 수 있습니다.</p></section>';
  const e=a.evidence,labels=['기본 확인','패치 구분','세부 패턴'],warnings={'no-official':'조건에 맞는 공식 표본이 없습니다.','small-official':'공식 표본이 10전 미만이라 해석 근거가 약합니다.','mixed-patches':'여러 패치의 결과가 섞여 있습니다. 패치별로 좁혀 비교하세요.','unknown-patch':'패치 출처가 미상인 표본이 있습니다.','aggregate-model':'자동 스크림은 간소화 계산입니다. 실제 엔진 경기와 합산하지 마세요.','unknown-practice':'일부 연습은 상세 또는 기존 요약만 남아 있습니다.','official-filter':'현재 대회 조건은 연습에 적용되지 않아 연습 표본을 제외했습니다.','incomplete-context':'전술·조합·픽 순서의 일부 맥락이 미상입니다.'};
  const pattern=p=>p.kind==='patch'?`${esc(p.patch)} · ${p.g}전 ${p.w}승`:p.kind==='copick'?`${esc(championLabel(db,p.champ))} 같은 쪽 동시 출전 · ${p.g}전 ${p.w}승`:p.kind==='order'?`드래프트 전체 첫 픽 ${p.opening}전 ${p.openingWins}승 · 후속 픽 ${p.followup}전 ${p.followupWins}승`:`전술 확인 ${p.known}전에서 ${p.axes.length}개 축의 설정이 서로 달랐습니다. 다른 조건도 함께 달라 개별 전술의 효과를 분리할 수 없습니다.`;
  return `<section id="analystreport"><h3>분석가의 기록 해석 · ${esc(db.teams[a.team]?.name||a.team)}</h3><p>해석 범위: ${labels[a.level]}${a.available?'':' · 분석가 지원 없음'} · 공식 ${e.official}전 · 공식 패치 ${e.officialPatches}종 · 연습 패치 ${e.practicePatches}종 · 현재 패치 공식 ${e.currentPatchGames}전</p>${a.warnings.length?'<ul>'+a.warnings.map(k=>'<li>'+warnings[k]+'</li>').join('')+'</ul>':'<p>확인된 출처 범위에서 표본을 살펴봅니다.</p>'}${a.patterns.length?'<ul>'+a.patterns.map(p=>'<li>'+pattern(p)+'</li>').join('')+'</ul>':'<p>현재 해석 범위에서는 기본 표본과 주의점을 확인합니다.</p>'}<small>데이터 전문성·업무 분산·중복 효과를 반영해 설명 범위를 정합니다. 원자료와 집계 수치는 분석 능력에 따라 바뀌지 않습니다. 해석 범위와 10전 기준은 가상 게임 정책이며 실제 능력 수치나 성공 확률이 아닙니다. 패치·동시 출전 목록은 빈도순이며 승률의 우열이나 추천 조합이 아닙니다. 패치 목록은 상위 3종, 동료는 상위 3명입니다. 적은 표본·상대·패치·다른 전술이 함께 영향을 주므로 인과적 효과나 정답을 뜻하지 않습니다.</small></section>`;
}
function patchPracticeComparisonCard(db,filter,cid=null){
  const a=ownPracticeComparison(db,filter,cid);if(!a.allowed)return '<section id="practicecomparison"><h3>우리 구단 스크림·공식 경기</h3><p>현재 관리 권한이 있는 구단·2군만 조회할 수 있습니다.</p></section>';
  const row=(label,x)=>`<tr><th>${label}</th><td>${x.games}전</td><td>${x.wins}승</td><td>${x.games?Math.round(x.wins/x.games*100)+'%':'표본 없음'}</td></tr>`;
  return `<section id="practicecomparison"><h3>우리 구단 스크림·공식 경기 · ${esc(db.teams[a.team]?.name||a.team)}</h3><div class="scroll"><table><thead><tr><th>기록 종류</th><th>출전</th><th>승리</th><th>승률</th></tr></thead><tbody>${row('실제 엔진 스크림',a.engine)}${row('간소화 계산 스크림',a.aggregate)}${row('공식 경기',a.official)}</tbody></table></div><p>스크림 상세 미상 ${a.unknownGames}전 · 기존 요약만 ${a.legacyGames}전</p><small>${a.officialOnly?'대회·시즌·스플릿·리그·국내/국제 제한은 스크림에 해당하지 않아 스크림 표본을 제외했습니다. ':''}기록된 같은 팀·패치·기간·상대·선수·챔피언 조건을 사용하며 선수·포지션은 같은 출전에 적용합니다. 각 종류의 승률 분모는 그 종류의 확인된 출전 수입니다. 자동 스크림은 간소화 계산이며 실제 엔진 경기와 구분합니다. 진영이 미상인 연습은 선택 진영으로 추정하지 않습니다. 미상/기존 요약 수는 선수·챔피언·포지션·진영 상세 조건 전의 확인 가능한 기간·패치·상대 기준이며 기존 요약의 지역도 추정하지 않습니다. 과거 요약에서 출전 상세를 복원하지 않으며 공식 메타에는 연습을 합산하지 않습니다. 적은 표본·패치·상대 차이가 영향을 주며 연습 승률이 공식 성적 향상을 보장하지 않습니다.</small></section>`;
}
function patchOwnTacticCard(db,filter,cid=null){
  const a=ownTacticInsights(db,filter,cid);if(!a.allowed)return '<section id="owntacticmeta"><h3>우리 구단의 기록 전술</h3><p>현재 관리 권한이 있는 구단·2군만 조회할 수 있습니다.</p></section>';
  const labels={aggression:'교전 회피 ↔ 교전 주도',risk_tolerance:'안정 지향 ↔ 위험 감수',objective_priority:'킬·교전 지향 ↔ 오브젝트 지향',vision_investment:'성장 투자 ↔ 시야 투자',scaling_preference:'초반 지향 ↔ 후반 지향'},name=db.teams[a.team]?.name||a.team;
  const axes=a.axes.map(x=>`<article class="card"><b>${esc(labels[x.key])}</b><p>${x.settings.length?x.settings.map(s=>s.value+' · '+s.g+'전 '+s.w+'승 ('+Math.round(s.wr*100)+'%)').join('<br>'):'확인 표본 없음'}</p><small>확인된 설정 ${x.distinct}종 · 빈도순 상위 6종</small></article>`).join('');
  return `<section id="owntacticmeta"><h3>우리 구단의 기록 전술 · ${esc(name)}</h3><p>${cid?'선택 챔피언 출전 · ':''}필터 출전 ${a.sample}쪽 · 전술 확인 ${a.known}쪽 · 미상 ${a.unknown}쪽</p><div class="cards">${axes}</div><small>0은 왼쪽, 100은 오른쪽 성향입니다. 경기 시작 시 관리 권한 아래 기록한 설정만 사용하며 현재 값으로 과거를 채우지 않습니다. 승률 분모는 각 설정의 확인된 출전 수입니다. 상대 전술의 정확한 값은 조회하지 않습니다. 적은 표본·패치·상대·다른 전술 축이 영향을 주므로 개별 설정의 인과적 효과나 추천 점수를 뜻하지 않습니다.</small></section>`;
}
function viewPatch(){
  const pt=DB.patches, list=[...pt.list].reverse(), prev=[...(pt.prev||[])].reverse();
  const rid=PSET.region==='GLOBAL'?null:PSET.region,{comps,patches,seasons,splits,leagues}=metaHistoryFacets(DB),today=DB.worldDate,from=PSET.period==='30'?addDays(today,-30):PSET.period==='90'?addDays(today,-90):PSET.period==='YEAR'?today.slice(0,4)+'-01-01':null,filter={region:rid||undefined,patch:PSET.patch==='ALL'?undefined:PSET.patch,comp:PSET.comp==='ALL'?undefined:PSET.comp,season:PSET.season==='ALL'?undefined:PSET.season,year:PSET.year||undefined,split:PSET.split==='ALL'?undefined:PSET.split,league:PSET.league==='ALL'?undefined:PSET.league,scope:PSET.scope==='ALL'?undefined:PSET.scope,position:PSET.position==='ALL'?undefined:PSET.position,team:PSET.team&&PSET.team!=='ALL'?PSET.team:undefined,player:PSET.player&&PSET.player!=='ALL'?PSET.player:undefined,opponent:PSET.opponent&&PSET.opponent!=='ALL'?PSET.opponent:undefined,color:PSET.color&&PSET.color!=='ALL'?PSET.color:undefined,from:from||undefined,to:PSET.period==='ALL'?undefined:today},filtered=!!(filter.patch||filter.comp||filter.season||filter.year||filter.split||filter.league||filter.scope||filter.position||filter.from||filter.team||filter.player||filter.opponent||filter.color),mt=filtered?metaTableFiltered(DB,filter):metaTable(DB,rid),G=mt[0]?.sample||0;
  const rows=mt.filter(x=>(PSET.role==='ALL'||x.c.roles.includes(PSET.role))&&(!PSET.q||championDisplayName(x.c).toLowerCase().includes(PSET.q.toLowerCase())||x.c.name.toLowerCase().includes(PSET.q.toLowerCase())));
  const {ranks,observed,tiers}=championTierLabels(DB,mt);
  const tier=x=>tiers.get(x.c.id);
  if(!observed)rows.sort((a,b)=>(ranks.get(a.c.id)??2)-(ranks.get(b.c.id)??2));
  const dc=PSET.champ&&DB.patch.champions[PSET.champ], ds=dc&&dc.skills, mi=dc?championMetaInsights(DB,dc.id,filter):null;
  const insightList=(arr,nameFn)=>arr&&arr.length?arr.map(([id,x])=>esc(nameFn(id))+' '+x.g+'전 '+Math.round(x.w/Math.max(1,x.g)*100)+'%').join(' · '):'표본 없음';
  const insight=dc&&mi&&(mi.players.length||mi.teams.length||mi.matchups.length||mi.recent.length)?'<section id="champmeta"><h4>대회 메타 인사이트</h4><div class="cards"><article class="card"><b>주요 선수</b><p>'+insightList(mi.players,id=>DB.players[id]?.name||id)+'</p></article><article class="card"><b>주요 팀</b><p>'+insightList(mi.teams,id=>DB.teams[id]?.name||id)+'</p></article><article class="card"><b>동일 포지션 매치업</b><p>'+insightList(mi.matchups,id=>championLabel(DB,id))+'</p></article><article class="card"><b>최근 흐름</b><p>'+(mi.recent.length?mi.recent.map(x=>x.win?'W':'L').join(' · '):'표본 없음')+'</p></article></div></section>':'';
  const detail=dc?`<section id="champdetail"><div class="cfghead"><h3>${esc(championDisplayName(dc))}</h3><button class="ghost sm2" id="pclose">닫기</button></div><p>${dc.roles.map(r=>ROLE_KO[r]).join('/')} · ${esc(CLASS_KO[dc.cls])} · ${esc(dc.dmg)} · 프로 ${championProEligible(DB,dc)?'사용 가능':`사용 제한 (~${esc(dc.proEligibleDate||'')})`}</p><div class="fin"><div><span>체력</span><b>${Math.round(dc.base.hp)}</b><small>+${dc.base.hpg}/레벨</small></div><div><span>방어력 / 마법 저항력</span><b>${Math.round(dc.base.arm)} / ${Math.round(dc.base.mr)}</b><small>+${dc.base.armg} / +${dc.base.mrg}</small></div><div><span>공격력</span><b>${Math.round(dc.base.ad)}</b><small>+${dc.base.adg}/레벨</small></div><div><span>공속 / 성장</span><b>${dc.base.as}</b><small>+${dc.base.asg}%</small></div><div><span>사거리 / 이동속도</span><b>${dc.base.range} / ${dc.base.ms}</b></div><div><span>자원</span><b>${dc.base.resource||'없음'}</b><small>${dc.base.resource?`성장 +${dc.base.resourceg} · 회복 ${dc.base.resourceRegen}`:''}</small></div></div><h4>${dc.detailSource==='riot_ddragon'?'패치 원천 연동 스킬 데이터':'스킬 시뮬레이션 데이터'}</h4><div class="cards">${Object.values(ds||{}).map(sk=>`<article class="card"><b>${sk.slot}${sk.name?` · ${esc(sk.name)}`:''}</b><p>${sk.sourceDescription?esc(sk.sourceDescription):(sk.kind==='ultimate'?'궁극기':sk.kind==='passive'?'패시브':'기본 스킬')+' · '+(sk.damageType?sk.damageType+' · ':'')+sk.effects.map(esc).join(', ')}</p><small>${sk.cooldown?` · 재사용 ${sk.cooldown}초`:''}${sk.baseDamage?.length?` · 기본 피해 ${sk.baseDamage.join('/')}`:''}${Object.keys(sk.ratios||{}).length?` · 계수 ${Object.entries(sk.ratios).map(([k,v])=>k.toUpperCase()+' '+v).join(', ')}`:''}${sk.cc?` · CC ${esc(sk.cc.type||'있음')}${sk.cc.duration?' '+sk.cc.duration+'초':''}`:''}${sk.heal?' · 회복':''}${sk.shield?' · 보호막':''}${skillRangeText(sk,dc)?' · '+skillRangeText(sk,dc):''}</small></article>`).join('')}</div></section>`:'';
  const sysRows=patchEvidenceRows(DB),activeItems=Object.values(DB.patch.itemDefs||{}).filter(x=>x.active!==false),activeRunes=Object.values(DB.patch.runeDefs||{}).filter(x=>x.active!==false);
  const topSystem=(kind,defs)=>defs.map(d=>({d,e:systemUsageEvidence(DB,kind,d.id,sysRows)})).filter(x=>x.e.eligible>0).sort((a,b)=>b.e.usage-a.e.usage).slice(0,5).map(x=>esc(x.d.name)+' '+Math.round(x.e.usage*100)+'%').join(' · ')||'아직 표본 없음';
  const tierCount=Object.fromEntries(['starter','component','boots','final','consumable','special'].map(k=>[k,activeItems.filter(x=>x.tier===k).length])),runeTree=Object.values(DB.patch.runes||{}).map(st=>esc(st.nameKo||st.name||st.key)+' '+(st.slots||[]).reduce((n,s)=>n+s.filter(id=>DB.patch.runeDefs?.[id]?.active!==false).length,0)+'개').join(' · ');
  const systemMeta=`<section><h3>아이템 / 룬 메타</h3><div class="cards"><article class="card"><b>아이템 ${activeItems.length}개 활성</b><p>${topSystem('item',activeItems)}</p><small>시작 ${tierCount.starter} · 조합 ${tierCount.component} · 장화 ${tierCount.boots} · 완성 ${tierCount.final} · 소모품 ${tierCount.consumable} · 특수 ${tierCount.special}. </small></article><article class="card"><b>룬 ${activeRunes.length}개 활성</b><p>${topSystem('rune',activeRunes)}</p><small>${runeTree}. </small></article></div></section>`;

  return `<section class="teamhead"><h2>패치 ${esc(DB.patch.id)}</h2><p class="hint">챔피언 ${Object.keys(DB.patch.champions).length}명 · 공식 데이터 ${DB.patch.championSource?.matched||0}/${DB.patch.championSource?.total||Object.keys(DB.patch.champions).length} · 한국어 설명 ${DB.patch.championSource?.localized||0}/${DB.patch.championSource?.total||Object.keys(DB.patch.champions).length} · 아이템 ${activeItems.length} · 룬 ${activeRunes.length} · ${filtered?'기록 필터':'누적/감쇠 참고'} 표본 ${G}판${pt.nextDate?` · 다음 패치 ${esc(pt.nextDate)}`:''}</p></section>
  ${detail}${insight}${dc?patchCompositionCard(DB,dc.id,filter)+patchDraftOrderCard(DB,dc.id,filter):''}${systemMeta}${patchOpponentReport(DB,PSET,filter,PSET.champ)}${patchParticipantControls(DB,PSET)}${patchSideCoverageCard(DB,filter)}${patchOwnTacticCard(DB,filter,PSET.champ)}${patchPracticeComparisonCard(DB,filter,PSET.champ)}${patchAnalystCard(DB,filter,PSET.champ)}<p class="hint">${filtered?'기록 필터':'누적/감쇠 참고'} 표본 ${G}판. 픽·승률은 선택한 쪽${filter.player?'의 선택 선수':''} 기준이며 밴은 경기 전체 노출입니다. 조건이 맞지 않거나 ID가 미상인 기록을 임의로 포함하지 않습니다.</p>${patchBanAttributionCard(DB,filter,PSET.champ)}
  <section><h3>챔피언 티어리스트</h3><p class="hint">${observed?"대회 밴픽 기준":"현재 패치 예상 티어"}</p><div class="controls"><label>지역<select id="pregion"><option value="GLOBAL">글로벌</option>${Object.values(DB.regions).map(r=>`<option value="${r.id}"${PSET.region===r.id?' selected':''}>${esc(r.name||r.leagueName||r.id)}</option>`).join('')}</select></label><label>패치<select id="ppatch"><option value="ALL">전체</option>${patches.map(x=>`<option value="${esc(x)}"${PSET.patch===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>대회<select id="pcomp"><option value="ALL">전체</option>${comps.map(x=>`<option value="${esc(x)}"${PSET.comp===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>기간<select id="pperiod"><option value="ALL">전체</option><option value="30"${PSET.period==='30'?' selected':''}>최근 30일</option><option value="90"${PSET.period==='90'?' selected':''}>최근 90일</option><option value="YEAR"${PSET.period==='YEAR'?' selected':''}>올해</option></select></label><label>연도<input id="pyear" type="number" min="2026" value="${esc(PSET.year)}" placeholder="전체"></label><label>시즌<select id="pseason"><option value="ALL">전체</option>${seasons.map(x=>`<option value="${esc(x)}"${PSET.season===x?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>스플릿<select id="psplit"><option value="ALL">전체</option>${splits.map(x=>`<option value="${esc(x)}"${String(PSET.split)===String(x)?' selected':''}>${esc(SPLIT_NAME?.[x]||x)}</option>`).join('')}</select></label><label>리그<select id="pleague"><option value="ALL">전체</option>${leagues.map(x=>`<option value="${esc(x)}"${PSET.league===x?' selected':''}>${esc((DB.regions[x]&&DB.regions[x].leagueName)||x)}</option>`).join('')}</select></label><label>범위<select id="pscope"><option value="ALL">전체</option><option value="DOM"${PSET.scope==='DOM'?' selected':''}>국내</option><option value="INTL"${PSET.scope==='INTL'?' selected':''}>국제</option></select></label><label>실제 픽<select id="pposition"><option value="ALL">전체</option><option value="TOP"${PSET.position==='TOP'?' selected':''}>탑</option><option value="JGL"${PSET.position==='JGL'?' selected':''}>정글</option><option value="MID"${PSET.position==='MID'?' selected':''}>미드</option><option value="ADC"${PSET.position==='ADC'?' selected':''}>원딜</option><option value="SUP"${PSET.position==='SUP'?' selected':''}>서포터</option></select></label><label>포지션<select id="prole"><option value="ALL">전체</option>${ROLES.map(r=>`<option value="${r}"${PSET.role===r?' selected':''}>${ROLE_KO[r]}</option>`).join('')}</select></label><label>검색<input id="pq" value="${esc(PSET.q)}" placeholder="챔피언 이름"></label></div>
  <div class="scroll"><table class="champs"><thead><tr><th>티어</th><th>챔피언</th><th>포지션</th><th>역할군</th><th>밴픽률</th><th>픽</th><th>밴</th><th>승률</th><th>프로 사용</th><th>초반</th><th>후반</th><th>CC</th><th>폭딜</th></tr></thead><tbody>
  ${rows.slice(0,60).map(x=>`<tr><td><b class="tier t${tier(x)}">${tier(x)}</b></td><td><button class="linklike" data-champ="${x.c.id}"><b>${esc(championDisplayName(x.c))}</b></button></td><td>${x.c.roles.map(r=>ROLE_KO[r]).join('/')}</td><td>${CLASS_KO[x.c.cls]}</td><td class="num">${Math.round(x.pres*100)}%</td><td class="num">${x.p}</td><td class="num">${x.b}</td><td class="num">${x.wr===null?'—':Math.round(x.wr*100)+'%'}</td><td>${x.eligible?'<span class="hi">가능</span>':`<span class="lo">제한</span><small>${esc(x.c.proEligibleDate||'')}</small>`}</td><td><span class="pip" style="--v:${x.c.kit.early}">${x.c.kit.early}</span></td><td><span class="pip" style="--v:${x.c.kit.late}">${x.c.kit.late}</span></td><td><span class="pip" style="--v:${x.c.kit.cc}">${x.c.kit.cc}</span></td><td><span class="pip" style="--v:${x.c.kit.burst}">${x.c.kit.burst}</span></td></tr>`).join('')}
  </tbody></table></div>${rows.length>60?`<p class="hint">상위 60명만 표시합니다. 포지션이나 검색으로 좁혀 보세요.</p>`:''}</section>
  <section><h3>패치 노트</h3>${list.length?list.map((p,i)=>`<details class="pnote"${i===0?' open':''}><summary><b>${esc(p.id)}</b> <small>${esc(p.date)}${p.major?' · 대형 패치':''} · 변경 ${p.notes.length}건</small></summary><ul>${p.notes.map(n=>`<li>${noteText(n)}</li>`).join('')}</ul></details>`).join(''):'<p class="empty">커리어를 시작하면 시즌 개막 패치가 적용됩니다.</p>'}
  ${prev.length?`<details class="pnote"><summary>지난 시즌 패치 ${prev.length}개</summary>${prev.map(p=>`<p><b>${esc(p.id)}</b> <small>${esc(p.date)}</small><br>${p.notes.map(noteText).join(' · ')}</p>`).join('')}</details>`:''}</section>`;
}
function bindPatchParticipants(){for(const [id,key] of [['pteam','team'],['pplayer','player'],['popponent','opponent'],['pcolor','color'],['pplayersearch','playerSearch']])$('#'+id).onchange=e=>{PSET[key]=e.target.value;nav()}}
function bindPatch(){bindPatchParticipants();bindOpponentPreparation();document.querySelectorAll('[data-champ]').forEach(b=>b.onclick=()=>{PSET.champ=b.dataset.champ;nav()});if($('#pclose'))$('#pclose').onclick=()=>{PSET.champ=null;nav()};$('#pregion').onchange=e=>{PSET.region=e.target.value;nav()};$('#ppatch').onchange=e=>{PSET.patch=e.target.value;nav()};$('#pcomp').onchange=e=>{PSET.comp=e.target.value;nav()};$('#pperiod').onchange=e=>{PSET.period=e.target.value;nav()};$('#pyear').onchange=e=>{PSET.year=e.target.value;nav()};$('#pseason').onchange=e=>{PSET.season=e.target.value;nav()};$('#psplit').onchange=e=>{PSET.split=e.target.value;nav()};$('#pleague').onchange=e=>{PSET.league=e.target.value;nav()};$('#pscope').onchange=e=>{PSET.scope=e.target.value;nav()};$('#pposition').onchange=e=>{PSET.position=e.target.value;nav()};$('#prole').onchange=e=>{PSET.role=e.target.value;nav()};$('#pq').onchange=e=>{PSET.q=e.target.value;nav()}}
