export const ENGINE_MODULES = [
  'champion-source.js',
  'system-source.js',
  'engine.js',
  'draft.js',
  'data.js',
  'champs2.js',
  'content-naming.js',
  'meta.js',
  'patch.js',
  'series.js',
  'competition.js',
  'player.js',
  'development.js',
  'player-relations.js',
  'world.js',
  'season.js',
  'offseason.js',
  'save.js',
  'roster.js',
  'lineup.js',
  'office.js',
  'finance.js',
  'contracts.js',
  'scouting.js',
  'transfer.js',
  'staff.js',
  'scrim.js',
  'features.js',
  'role-conversion.js',
  'draft-analysis.js',
  'career.js',
];

export const UI_MODULES = [
  'ui-patch.js',
  'ui-market.js',
  'ui-champion.js',
  'ui-setup.js',
  'ui-match.js',
  'ui-manager.js',
  'ui-data.js',
  'ui-player.js',
  'ui-roster.js',
  'ui-draft.js',
  'ui-season.js',
  'app.js',
];

export const ARTIFACT_MODULES = [...ENGINE_MODULES, ...UI_MODULES];
